Add validation for battery path
The validation checks if the path passed in the -b parameter is valid
(it only checks if there is a path, not if is a battery) and also test
if the default path is correct.

diff --git a/battery b/battery
--- a/battery
+++ b/battery
@@ -173,7 +173,15 @@ while getopts ":g:m:w:tab:" opt; do
       pmset_on=1
       ;;
     b)
-      battery_path=$OPTARG
+	  if [ -d $OPTARG ]; then
+		battery_path=$OPTARG
+	  else
+		echo "Battery not found, trying to use default path..."
+	    if [ ! -d $battery_path ]; then
+		  echo "Default battery path is also unreachable"
+		  exit 1
+		fi
+	  fi
       ;;
     \?)
       echo "Invalid option: -$OPTARG"
