Added support for multiple_batteries

diff --git a/battery b/battery
--- a/battery
+++ b/battery
@@ -75,26 +75,20 @@ battery_charge() {
             fi
             ;;
         "Linux")
-            case $(cat /etc/*-release) in
-                *"Arch Linux"*|*"Ubuntu"*|*"openSUSE"*)
-                    battery_state=$(cat $battery_path/energy_now)
-                    battery_full=$battery_path/energy_full
-                    battery_current=$battery_path/energy_now
-                    ;;
-                *)
-                    battery_state=$(cat $battery_path/status)
-                    battery_full=$battery_path/charge_full
-                    battery_current=$battery_path/charge_now
-                    ;;
-            esac
-            if [ $battery_state == 'Discharging' ]; then
-                BATT_CONNECTED=0
-            else
-                BATT_CONNECTED=1
-            fi
-                now=$(cat $battery_current)
-                full=$(cat $battery_full)
-                BATT_PCT=$((100 * $now / $full))
+	         for battery_path in ${battery_paths[@]}; do
+                         battery_state=$(cat $battery_path/status)
+                         battery_full=$battery_path/energy_full
+                         battery_current=$battery_path/energy_now
+
+			 now=$(($now + $(cat $battery_current)))
+			 full=$(($full + $(cat $battery_full)))
+	  	 done
+		 #if [ $battery_state == 'Discharging' ]; then
+	         #    BATT_CONNECTED=0
+		 #elif [ $battery_state == 'Charging' ] || [ $battery_state == 'Full' ]; then
+	         #    BATT_CONNECTED=1
+		 #fi
+                 BATT_PCT=$((100 * $now / $full))
             ;;
     esac
 }
@@ -200,14 +194,10 @@ while getopts ":g:m:w:tzeab:p" opt; do
             ;;
         b)
             if [ -d $OPTARG ]; then
-                battery_path=$OPTARG
-            else
-                >&2 echo "Battery not found, trying to use default path..."
-                if [ ! -d $battery_path ]; then
-                    >&2 echo "Default battery path is also unreachable"
-                    exit 1
-                fi
-            fi
+                battery_paths+=("$OPTARG")
+	    else
+		>&2 echo "Could not find battery at path \"$OPTARG\""
+	    fi
             ;;
         \?)
             echo "Invalid option: -$OPTARG"
@@ -219,6 +209,14 @@ while getopts ":g:m:w:tzeab:p" opt; do
             ;;
     esac
 done
+if [ -z $battery_paths ]; then
+    >&2 echo "Batteries not found, trying to use the default path..."
+    if [ ! -d $battery_path ]; then
+        >&2 echo "Default battery path is also unreachable"
+        exit 1
+    fi
+    battery_paths=("$battery_path")
+fi
 
 battery_charge
 apply_colors
